<Send_Button>:
    GridLayout:
        cols: 1
        size: 200, 200
        pos: 0, 0


        Button:
            text: 'Schmerz'
            background_color: (0, 1, 0, 1)
            on_press: root.pressed()
<Text_box>:
    orientation: "vertical"
    BoxLayout:
        size: 600, 200
        TextInput:
            size_hint_x: 20
<Chatwindow>
    button: send_button



    Send_Button:
        id: send_button
